---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deployment
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: my-deployment
      name: my-deployment
    spec:
      containers:
        - name: my-deployment
          image: yovelchen/myappimg:latest
          volumeMounts:
            - readOnly: true
              mountPath: /app/templates
              name: html-files
          ports:
            - containerPort: 5000
      volumes:
        - name: html-files
          configMap:
            name: my-app-content


